# Generated by Django 4.0.6 on 2022-07-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_skills_options_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomplishments',
            new_name='Accomplishment',
        ),
        migrations.AlterModelOptions(
            name='accomplishment',
            options={'verbose_name_plural': 'accomplishments'},
        ),
    ]
