# Generated by Django 4.0.6 on 2022-07-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_rename_accomplishments_accomplishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alternate_email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='alternate_phone',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_alternate_contact',
            field=models.BooleanField(default=False),
        ),
    ]
