# Generated by Django 4.0.6 on 2022-08-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_accomplishment_image_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='image_dir',
            field=models.FilePathField(path='mainsite/static/mainsite/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_dir',
            field=models.FilePathField(path='mainsite/static/mainsite/images/'),
        ),
    ]
