# Generated by Django 4.0.6 on 2022-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_alter_accomplishment_image_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_icon_name',
            field=models.CharField(default='fa-code', max_length=16),
        ),
    ]
