# Generated by Django 4.0.6 on 2022-08-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_skills_skill_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_icon_name',
            field=models.CharField(default='fa-code', max_length=32),
        ),
    ]
