# Generated by Django 4.0 on 2022-09-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_alter_skills_skill_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='image_dir',
            field=models.FilePathField(path='{% static %}'),
        ),
    ]
