# Generated by Django 4.0 on 2022-09-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_alter_accomplishment_image_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='image_dir',
            field=models.FilePathField(path='mainsite/static/mainsite/images/'),
        ),
    ]
